services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ugc_surveys
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      PYTHONUNBUFFERED: "1"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
