# Generated by Django 5.1.6 on 2026-04-26 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Один вариант"),
                            ("multiple", "Несколько вариантов"),
                            ("text", "Свободный ответ"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="Тип вопроса",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
            },
        ),
        migrations.CreateModel(
            name="SurveySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начат"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершён"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия опроса",
                "verbose_name_plural": "Сессии опросов",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(blank=True, verbose_name="Текстовый ответ"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Отвечен"),
                ),
            ],
            options={
                "verbose_name": "Ответ пользователя",
                "verbose_name_plural": "Ответы пользователей",
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=500, verbose_name="Текст варианта"),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Порядок")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="surveys.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
                "ordering": ["order"],
            },
        ),
    ]
