# Generated by Django 5.1.6 on 2026-04-26 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="surveys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="surveys.survey",
                verbose_name="Опрос",
            ),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="surveys.survey",
                verbose_name="Опрос",
            ),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="surveys.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="selected_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_answers",
                to="surveys.answeroption",
                verbose_name="Выбранные варианты",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="surveys.surveysession",
                verbose_name="Сессия",
            ),
        ),
        migrations.AddIndex(
            model_name="answeroption",
            index=models.Index(
                fields=["question", "order"], name="option_question_order_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answeroption",
            unique_together={("question", "order")},
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["author"], name="survey_author_idx"),
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(fields=["created_at"], name="survey_created_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["survey", "order"], name="question_survey_order_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("survey", "order")},
        ),
        migrations.AddIndex(
            model_name="surveysession",
            index=models.Index(
                fields=["user", "survey"], name="session_user_survey_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="surveysession",
            unique_together={("user", "survey")},
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(
                fields=["session", "question"], name="answer_session_question_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(fields=["question"], name="answer_question_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("session", "question")},
        ),
    ]
