# Generated by Django 5.1.6 on 2026-04-28 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["is_active", "-created_at"], name="survey_active_created_idx"
            ),
        ),
    ]
